### ISSUE TITLE
What is purpose of setting name to GC data?

### ISSUE THREAD

**Issue by JerabekJakub** [asamm/locus-api#10]
https://github.com/asamm/locus-api/blob/0a64f972b2a96ade78d4d363d892e557a506e3c1/locus-api-android-sample/src/main/java/com/asamm/locus/api/sample/utils/SampleCalls.java#L494

Name of the imported cache is taken from `Waypoint` constructor, I haven't found inserted value anywhere in the geocache listing. Why is this setter mandatory?

+1 for the name. ;-)

**Comment by menion** [comment]
Good day Jakub,
very good question. Reason for this parameter is most probably lost in history. Even in GPX parser in app, the loaded name is set on the first line to `Waypoint.java` class, in the second line is the same value set to `GeocachingData.java` class.
Agree this is not the ideal solution. From compatibility reasons and also because both values are used directly in Locus Map app, we should keep it as is. But thanks for bringing this up.
