### ISSUE TITLE
(Waypoint) point.getParameterStyleName() returns null for icons from Garmin set

### ISSUE THREAD

**Issue by tripleSevenRada** [asamm/locus-api#16]
I get the waypoints like this: track.getWaypoints(). It looks like all icons from "Garmin" set return null, but I have specifically checked just a few.

![screenshot_20190104-170406](https://user-images.githubusercontent.com/27644227/51316092-ffef6e80-1a53-11e9-9314-6194beb524cf.png)
![screenshot_20190104-171816highlight](https://user-images.githubusercontent.com/27644227/51316093-ffef6e80-1a53-11e9-8eea-0c00a85190cf.png)

**Comment by menion** [comment]
Hello,
interesting. You get track as a reaction on click in track bottom "share" menu, so with `LocusUtils.handleIntentTrackTools`? If so, how you created these two points in the track, so I may try to simulate exactly your steps. Thanks

**Comment by tripleSevenRada** [comment]
Hi,
Waypoints creation:
Currently in my Locus Map 3.35.2 the only way I can get custom waypoints created and exported in track is to "include navigation hints" first. Then I can see that blue plus button in waypoint section of track overview. If there are no waypoints previously created, there is the background saying "nothing here yet, tap plus to add some" but no plus to tap. (This is something I've been meaning to report too but obviously not api related, imho custom waypoints in tracks are great, what I do leverages them).
So i go: plus button, Add new, then the "black dot and circle", select on map, left blue "tick" button, then select icon, save in top toolbar.
Track export:
Yes, bottom "share" menu, then in my activity some async call like
val track = LocusUtils.handleIntentTrackTools(activity, intent)
Thanks, will be happy to provide more details or video

**Comment by menion** [comment]
Hello, ah perfect, simulated and ...
This is little unfortunate. What happens here is the result of internal app optimization.
All basic icons that do not need any additional information are available under function you find and use:  `getParameterStyleName()`.

Anyway base system app use for storing point styles is in public objects `styleNormal` and `styleHighlight`. If you check the content of `styleNormal`, I'm sure, there will be under `iconStyle.iconHref` required icon. It happens here because this icon is centered, so there is also `hotSpot` object set to center-center. With this powerful object, is possible to rotate icon, resize etc. Anyway, for the huge number of points, it will be quite overhead. That's why internally app uses two styling mechanisms.

Sorry for the confusion. I cannot promise improvement now, but will definitely keep in mind this when writing docs or any new public functions.
With this information, are you able to deal with your use-case?

**Comment by tripleSevenRada** [comment]
Well, all I need for my use case is to get hold of some String that definitely maps to some icon and only to that icon. If the objects you are  referencing  are public, it should be fairly easy to redirect my logic. My mappings to Garmin's set of 16 coursepoints are not that fine grained anyway and they default to GENERIC in most cases. But still I try to keep consistency.
What bothers me more is the missing blue plus button in case of no navigation hints a routing engine produced (activity layout says tap plus to add some but there is no plus to tap).
    Anyway thank you a lot.

**Comment by menion** [comment]
Yes, they are public and you will have no problem to access it.

What I internally use in app is this:

```
        String styleName = pt.getParameterStyleName();
        if (Validator.isValid(styleName)) {
            return styleName;
        }

        if (pt.styleNormal != null && pt.styleNormal.getIconStyleIconUrl() != null) {
            return pt.styleNormal.getIconStyleIconUrl();
        }
        return "";
```
Hope this helps.

About the issue with missing "+" button. It is already solved for some time in the latest Beta versions. The new public version will be out most probably within next 10 days.

**Comment by tripleSevenRada** [comment]
Of course this helps, thanks!
