### ISSUE TITLE
Please share your adaptive launcher icon

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#18]
Would be nice if you could share the updated adaptive launcher icon from locus maps application in your sample app:
https://github.com/asamm/locus-api/tree/master/locus-api-android-sample/_data/graphics

Kind Regards
Falco

**Comment by menion** [comment]
Good day Falco,
sorry for the delay, little extra work with recent Locus Map update.

Please check this directory, it should contain all you need:
> https://github.com/asamm/locus-api/tree/master/_data/ic_launcher_new

Let me know if there will be any problem.

**Comment by arcao** [comment]
Good day Menion,

Because Google Play requires icon in 512px it would be great to have the foreground and background image at least in this resolution or better in the curves. Could you please share that images for us?

PS: I can create images for different dpi in a graphic editor (in my case Affinity Designer). I've already had a template for it.

Thank you.

**Comment by Falcosc** [comment]
@arcao Down scaling can be done directly in android studio. During image import it will ask you for which DPI you would like to create down scaled versions

@menion  Thank you for the fast response, would be nice to have vector or 512px

**Comment by menion** [comment]
Hello Arcao, Falco,
I've added bigger 720x720 icon I have from our designer to zip file. It is created as all adaptive icons, from two parts. On Google Play are some new requirements and I'm not sure what exactly they will need. But hopefully, this will be enough.

**Comment by Falcosc** [comment]
Thank you for your time.
