### ISSUE TITLE
Please provide a maven repo

### ISSUE THREAD

**Issue by jspricke** [asamm/locus-api#2]
Hi,

I'm working on bringing [WhereYouGo](https://github.com/biylda/WhereYouGo) to [F-Droid](http://f-droid.org), which uses locus-api as it's dependency. It would be great to get it from a maven repo, like [maven central](http://search.maven.org/) or [jcenter](https://bintray.com/bintray/jcenter). Thanks!

**Comment by menion** [comment]
Good day Jochen, nice to meet you.

Interesting you find this repository so soon as it's just a few days since I copy it on GitHub from [Bitbucket](https://bitbucket.org/asamm/locus-api) . Main reason was exactly what you need - whole Locus API available as a repo over jcenter. 

Unfortunately my skills with these repositories are still quite limited and after few hours of fight with various gradle scripts & bintray & Android build system cooperation, I just gave up.

Seems I'll have to give it a second try.

**Comment by jspricke** [comment]
Hi, nice to meet you too.

I've never used jcenter, but I tried https://jitpack.io/ today and it worked great. Would still be great to get locus-api to jcenter. I guess you need a `pom.xml` for that. Maybe [this](https://jitpack.io/com/github/asamm/locus-api/cd3656c/locus-api-cd3656c.pom) could serve as a start. Ping me, if you need help.

**Comment by menion** [comment]
Hello,
[Locus API](https://github.com/asamm/locus-api) and also [Locus API - Android](https://github.com/asamm/locus-api) projects are now available over Maven.

To use Locus API in, for example, WhereYouGo project, simply add 

`compile 'com.asamm:locus-api-android:0.2.2'`

as a project dependency. `Locus API` depends on `Locus API - Android` so no need to add it directly. Let me know if this works fine for you.

**Comment by jspricke** [comment]
Awesome, working fine.

Thanks a lot!
