### ISSUE TITLE
More nullable fields on update container since kotlin

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#21]
Could map location fields really be null?
I would like to create a pull request to make the following fields non null:
MapBottomRight
MapTopLeft
MapCenter

Would it make sense to make these not nullable?

**Comment by menion** [comment]
Good day Falco,
I see that with current implementation in the latest Locus Map, it should be no problem and map coordinates really should be nullable. Anyway, with version before 3.37, I'm not so sure.

Also, Storable system is not too efficient here. Because such change means that you will have to do
`var mapBottomRight: Location = Location(0.0, 0.0)` (so always init empty `Location`) and a moment later set this value to your wanted or already stored in `Storable`. So not too efficient here.

Suggest to stay with `updateContainer.mapBottomRight?.let()` system, ok?

**Comment by Falcosc** [comment]
Intention was to skip the null check instead of null check operator "?"

But you are right, an init would be more expensive.

Is storeable with constructor and final values better? This won't give any real word benefit and for that reason it should not be refactored. But would it make sense?

My solution is exception handling instead of null checks.
