### ISSUE TITLE
Live_tracking broadcast issue

### ISSUE THREAD

**Issue by Olexiyoo** [asamm/locus-api#34]
Hi!
I am trying to turn on / off live tracking via Tasker.
Broadcast 
_tasks:  { live_tracking_asamm:   { action: "start"  } }_
does not work,
but 
_tasks:  { live_tracking_asamm:   { action: "stop"  } }_
works as expected.
For live tracking, I have a single configuration with my own group. 
Locus 3.51.3 Pro, Android 11.
Regards!

**Comment by menion** [comment]
Hello,
thanks for opening this issue.

Do you see any information on the screen when Locus Map is running and you send this "Start" request? As I see, there is by accident wrote that the "name" parameter is optional. This is anyway incorrect. It has to be defined because the app needs to know which live tracking should be started!

So please, try to define also `name` parameter. In the app is defined at the bottom of the tracking profile detail screen as a small "Profile ID" value.

Let me know if it works now.

**Comment by Olexiyoo** [comment]
Hi!
Thanks for the answer. With Profile ID in "name" now broadcast works fine. It was not obvious that Profile ID should be substituted in "name". I previously tried typing in the my group name and it didn't work.
Regards!

**Comment by menion** [comment]
perfect. I've fixed documentation to correctly inform about this requirement.
