### ISSUE TITLE
Action Task Map Zoom Value does not match 

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#37]
Zoom Value used at action task map_zoom

https://github.com/asamm/locus-api/wiki/Action-tasks-(Broadcasts)#map_zoom

doesn't match to UpdateContainer mapZoomLevel

https://github.com/asamm/locus-api/blob/4759711ac504992e937344ba8171cb857ae6c0eb/locus-api-android/src/main/java/locus/api/android/features/periodicUpdates/UpdateContainer.kt#L152-L158

Is there a reason why map_zoom level 28 results into UpdateContainer mapZoomLevel 20?
And map_zoom value 28 is out of range according to https://github.com/asamm/locus-api/wiki/Action-tasks-(Broadcasts)#map_zoom

It is not importand, I just wanted to tell you that there is a mismatch.

I did test it with the Locus Map 4 (don't remember which version it was)

**Comment by menion** [comment]
Thanks Falco.
This is really inconsistent behavior. Internally Locus Map works with values starting with 8, not 0. 

Description in the UpdateContainer is wrong, should be "zoom 0 == whole world". Fixed.

Handling "map_zoom" is then incorrect and will be fixed in the next 4.1.1 version. So in the next version, supplied value 20 will be internally handled as "28", but again correctly reported over `UpdateContainer` as 20.

Thanks

**Comment by Falcosc** [comment]
Don't forget the wiki page, it tells value range is `[1-26]`
