### ISSUE TITLE
Why is it possible to disable animation of map_move_zoom 

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#40]
What is the purpose of map_move_zoom?

I guess it is used to animate the action because the old tasks don't support animation, or are the old tasks animated by default?

What is the difference between map_move_zoom and the old actions if you disable animation?

**Comment by menion** [comment]
Hello Falco,
good and quick observation :).

Reason for this update: https://help.locusmap.eu/topic/24841-map-scrollingpanning-with-carpe-iter

Unfortunately, I was not able to find out a method how to simply in the app, merge three separate actions (moveX, moveY, zoom) into single action where may be applied animation. Internally, I need to have all parameters at once to perform a single action.

That's why I've created this method. So yes, for now, the only difference is the toggle for animation (old methods are not animated at all, they are instant) and reduced options for the zoom (where I need integer value, no plus/minus).

I'm still not sure about this solution because it really mostly duplicated previous methods ...

**Comment by Falcosc** [comment]
Thanks for the explanation.

> quick observation :).

Well, since last month you did not stop to add new things. Each time I think I have completed an endpoint, only one or two days later a notification does pop up with new git commit or wiki changes 😄

**Comment by menion** [comment]
As I think about it, it looks to me like an optimal solution in the end. It simply combines location & zoom and adds a united parameter like 'animate' or 'keep_centering'. Maybe some more will appear later.

Anyway I think, we may consider it as a final solution. It will take some time till most of the users will update apps to a supported version, so for now, suggest using the existing solution ...

Hope you at least find in commits anything useful for you 😉
