### ISSUE TITLE
Broadcast receivers can't receive implicit intents on Android 8.0.0 (Android O)

### ISSUE THREAD

**Issue by arcao** [asamm/locus-api#5]
Hello,

In Android 8.0.0 (Android O) was introduced [broadcast limitation](https://developer.android.com/preview/features/background.html#broadcasts) which breaks any implicit broadcasts between two apps.

Fortunately explicit broadcast (broadcast which sent to specific receiver - has to be filled package name and class name in broadcast intent) works. So quick solution is to query broadcast receivers with package manager and in a loop send the intent to specific broadcast receiver.

Here is compatibility implementation for `sendBroadcast` which works for Android 8.0.0 (Note: Implicit broadcast can be [somehow disabled since Android 7 /API 24/](https://developer.android.com/topic/performance/background-optimization.html#further-optimization), thus this code use `queryBroadcastReceivers` for API 24 and up)
```java
  public static void sendBroadcastCompat(Context context, Intent intent) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
            context.sendBroadcast(intent);
            return;
        }
        
        Intent broadcastIntent = new Intent(intent);    
        PackageManager pm = context.getPackageManager();
        
        List<ResolveInfo> broadcastReceivers  = pm.queryBroadcastReceivers(broadcastIntent, 0);
        for(ResolveInfo info : broadcastReceivers) {
            broadcastIntent.setClassName(info.activityInfo.packageName, info.activityInfo.name);
            context.sendBroadcast(broadcastIntent);
        }
    }
```

**Comment by menion** [comment]
Good day Arcao,
in latest API version 0.2.10, issue should be solved.

Your implementation is usable for sending broadcasts from Locus Map to add-ons, but not opposite. In this case, all installed Locus apps may receive it, which is not wanted. In latest API, you always know with which Locus X version app communicate, so implicit broadcast to correct Locus Map may be always send.

Let me know if there will be any problem with it. On Locus Map side, implicit broadcasts (mainly for periodic updates) are enabled since version 3.24.0 , so it is well tested and secured to use on all Android versions.

**Comment by chandanitnou** [comment]
I send broadcast from activity, and I have a BroadcastReceiver declared in manface whit intent-filter , but when i send broadcast, i don't get onReceive is called<a href="https://eproductfinder.com/">.</a>

**Comment by hjgode** [comment]
List<ResolveInfo> broadcastReceivers  = pm.queryBroadcastReceivers(broadcastIntent, 0); will only find Manifest declared Intents, not BroadcastReceivers declared in code!
